### PR TITLE
Added code improvements

### PR DESCRIPTION
**Pull request by yvesmh**
Added IntelliJ output files to `.gitignore`

Fixed warnings in file `ExeploreGame.java`

Part of #10

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @yvesmh 
i would love to see more contributions from your side .

**Comment by srbcheema1** [comment]
@yvesmh 
i would be glad if you give a STAR to my repository

**Comment by yvesmh** [comment]
Sure @srbcheema1, starred :) thanks for accepting my contribution, and happy hacktoberfest!

**Comment by srbcheema1** [comment]
you are always welcome @yvesmh 
happy hactoberfest :smile:

**Pull request merged**
