### PR TITLE
Changing somes identation

### PR DESCRIPTION
**Pull request by caioz7**
Good day everyone,
Just a idea to Removing the _SuppressWarnings_ unused and including them in the class declaration, fixing the indentation in the src.

IDE used: Eclipse

### CODE REVIEW

**Comment by srbcheema1** [comment]
thanks for the PR @caioz7 
it is too large commit 
you must break have broken it into 2 separate commits 
1 for intendation fixing 
2 for warnings 
also i would like to ask is there any other change apart from this ?
because it is very difficult to find if there is logical or structural change in such large files

**Comment by caioz7** [comment]
Hi @srbcheema1 ,
sorry for that, i wish to make more changes in this weekend in front and back end when I must have more free time, theres no logical or structural changes, just some warning sign to remove in IDE.

If you want to ignore this pull request, I will undestand.

**Comment by caioz7** [comment]
Hi, @srbcheema1 
I close this pull request for be useless for this time.

**Comment by srbcheema1** [comment]
@caioz7 
sorry if i was wrong in conveying message .
i was not ignoring the PR .
i eager to merge it .
more over it was a great fix .
but all i wanted was to confirm that isn't there any logical change in the commit 
so that it would not create a difficulty for other developers to understand commits

**Comment by srbcheema1** [comment]
this branch is having some conflicts also .
you can do one thing pull latest master and you can make your changes there
make sure that one commit must do a particular type of work 
like there must be a separate commit for intendation .
separate commit for logical work .
separate commit for commenting . 
it is a good practice .

**Comment by caioz7** [comment]
Hi @srbcheema1 ,
this pr are closed cause soon I will open a new pr(with the sames changes), in parts and with more details.

Thx for the patient.

**Comment by srbcheema1** [comment]
ok thats great @caioz7 
i will be eager to see your next PR :)
happy coding :smile:

**Pull request closed without merging**
